#!/bin/sh
set -eux

make
git checkout -b tmp-deploy
git reset gh-pages
git checkout gh-pages
git add index.html elm.js ./*.css
git commit -m 'Deploy'
git checkout tmp-deploy
git reset master
git checkout master
git push origin gh-pages
